### ISSUE TITLE
Communicaton from Unity to Vue not working

### ISSUE THREAD

**Issue by ppVis** [Meqn/UnityWebGL.js#1]
Hi, thanks for your great plugin!

Everything is working fine except communication from unity to vue. I want to listen on a method listenToUnity() in Unity. My code in Vue looks like this:

`Unity.on("listenToUnity", () => console.log("I am listening to unity."));`

What do I have to do in Unity? Your docu says `__UnityLib__.showDialog(data)`, but I dont understand what I should do..

Can you help me please?

ppVis

**Comment by weeliem** [comment]
Hi, anyone solution on this? I having the same issue, unable to send message from webgl to vuejs method.

**Comment by ppVis** [comment]
I am not sure if that's a good solution but I got it working like that:

### In Unity script:

```
[DllImport("__Internal")]
private static extern void ObjectReady(string name);
	
void Start()
{
#if !UNITY_EDITOR && UNITY_WEBGL
        ObjectReady("ObjectXY");
#endif
}	
```
	
### In Assets/Plugins/WebGL/VueCom.jslib

```
mergeInto(LibraryManager.library, {
	ObjectReady: function (name) {
		var event = new CustomEvent("unityEventObjectReady", {
			detail: { objName: name },
		});
		window.dispatchEvent(event);
	},
});
```

### In Vue Script

```
onMounted(() => {
	Unity.create("#canvas");

	window.addEventListener("unityEventObjectReady", function (e) {
		console.log(e.detail);

	});
});
```


Does anyone know a way without CustomEvent and maybe directly calling a method?

**Comment by Meqn** [comment]
@ppVis 
Your way should work. 

```js
Unity.on('showDialog', (data: any) => {
  console.log(data)
  $('#dialog').show()
})
```

This code is to bind the showDialog method on the __UnityLib__ object.

**Comment by Meqn** [comment]
@weeliem @ppVis 

Sorry ！I’m a web developer. I don't know Unity3d development, I did it with my Unity development colleagues.

https://github.com/Meqn/UnityWebGL.js/issues/2#issuecomment-1066470357
