### ISSUE TITLE
Unity build loads twice

### ISSUE THREAD

**Issue by OctopussyO** [Meqn/UnityWebGL.js#16]
Hello!

We have an app with different games. User can select a game from map-page.
Each game uses unity. We have a wrapper component for unity.

The problem is that when you open the NEXT game unity build loads twice.

So, for example, you open the first game (unity build loads). Then you go to map-page and choose another game. When this _another_ game page is opened the build loads twice for some reason. 

Do you have any idea what could be the reason?

**Comment by OctopussyO** [comment]
https://dev.shadow-scratch.wall.black/chapters/1501/lessons/5028?demo-id=unity_release

**Comment by Meqn** [comment]
Sorry, I can't find the problem with your demo, please provide a simple example source code

**Comment by Meqn** [comment]
> https://dev.shadow-scratch.wall.black/chapters/1501/lessons/5028?demo-id=unity_release

@OctopussyO 
Sorry, I can't find the problem with your demo, please provide a simple example source code

**Comment by Meqn** [comment]
@OctopussyO 
upgrade to v3.2.0
