### ISSUE TITLE
unity和浏览器交互有demo吗

### ISSUE THREAD

**Issue by exile-yy** [Meqn/UnityWebGL.js#17]
或者说unity和vue3的交互

**Comment by Meqn** [comment]
文档底部有说明
https://github.com/Meqn/UnityWebGL.js#communication

[页面示例](https://stackblitz.com/edit/unity-webgl-vue2-demo?file=src%2FApp.vue) ：点击界面塔吊，执行 JS的弹窗

**Comment by Meqn** [comment]
@exile-yy Unity开发我不懂
