### ISSUE TITLE
Operation error

### ISSUE THREAD

**Issue by JamesNorrington** [Meqn/UnityWebGL.js#2]
Code cannot be run on unity2021，Can you provide a simple demo

**Comment by Meqn** [comment]
@JamesNorrington 
Sorry ！I’m a web developer. I don't know Unity3d development, I did it with my Unity development colleagues.

I asked my colleague and he intercepted a piece of code for me.

![unity-web](https://cdn.jsdelivr.net/gh/Meqn/store/imgs/20220314/image-20220314154159964-059698.png)

**Comment by Meqn** [comment]
@JamesNorrington 
see : https://github.com/Meqn/UnityWebGL.js#communication
