### ISSUE TITLE
[help] unity资源替换

### ISSUE THREAD

**Issue by StarDamnSucks** [Meqn/UnityWebGL.js#25]
我目前使用electron打包桌面程序，工具使用的是electron-vite，资源放在了resources目录下，打包后可以正常运行，但是不能替换unity资源内容，一旦进行替换就不能正确加载，根据开发者工具里的内容看像是loader.js被一并打包了，如果想要把unity的内容单独提取出来做热替换是否可行，如果可行我该怎么做，感谢

**Comment by Meqn** [comment]
> 我目前使用electron打包桌面程序，工具使用的是electron-vite，资源放在了resources目录下，打包后可以正常运行，但是不能替换unity资源内容，一旦进行替换就不能正确加载，根据开发者工具里的内容看像是loader.js被一并打包了，如果想要把unity的内容单独提取出来做热替换是否可行，如果可行我该怎么做，感谢

`loader.js` 其实不影响，主要是 资源文件变更。

**Comment by StarDamnSucks** [comment]
> @StarDamnSucks 你是要替换 unity资源文件？ 这个无法做到自动热更新，只能手动销毁和重建。
> 
> 本来vue组件想要做一个监听 unity资源地址变化，然后自动重载，但是想想没必要。因为资源更新了，其实资源地址是不变的。如果地址也要改变，相当于改变整个Unity应用实例了。这个只能重新创建新实例，Unity官方也不会提供方法，也没必要。
> 
> 不过可以在 `UnityWebgl.js` 内加一个 `reload(config)` 实例方法。 (你可以参考源码中的 `html` 示例)

我是指unity的资源文件不与项目文件打包在一起，这样的话文件可以进行替换，像这样的几个文件
![image](https://github.com/Meqn/UnityWebGL.js/assets/12879803/a8ba5d2f-8d5e-486c-916a-7eb4d67b0668)
当这些模型文件替换时unity可以加载新的资源文件，由于我这个是桌面端程序，不是web的，所以并不能使用cdn引入替换，非常感谢你的回答

**Comment by Meqn** [comment]
只要实例化配置的资源 path 不变，替换资源文件没有任何问题。
另：客户端也是可以引入网络资源的吧。

**Comment by StarDamnSucks** [comment]
> 只要实例化配置的资源 path 不变，替换资源文件没有任何问题。 另：客户端也是可以引入网络资源的吧。

资源path不变，但是我在electron的开发工具里看到的loader.js文件被打包进了asar中，我的文件资源在asar.unpacked中，所以一旦替换就不能正常运行，需要重新打包。
客户端可以引入网络资源，但是我这边没有网络资源的服务器用于部署这个。
在网上找了很久没有找到有人有同样的需求，没办法了只能想你请教了

**Comment by Meqn** [comment]
> > 只要实例化配置的资源 path 不变，替换资源文件没有任何问题。 另：客户端也是可以引入网络资源的吧。
> 
> 资源path不变，但是我在electron的开发工具里看到的loader.js文件被打包进了asar中，我的文件资源在asar.unpacked中，所以一旦替换就不能正常运行，需要重新打包。 客户端可以引入网络资源，但是我这边没有网络资源的服务器用于部署这个。 在网上找了很久没有找到有人有同样的需求，没办法了只能想你请教了

不好意思，这个场景我不太了解。

**Comment by StarDamnSucks** [comment]
> > > 只要实例化配置的资源 path 不变，替换资源文件没有任何问题。 另：客户端也是可以引入网络资源的吧。
> > 
> > 
> > 资源path不变，但是我在electron的开发工具里看到的loader.js文件被打包进了asar中，我的文件资源在asar.unpacked中，所以一旦替换就不能正常运行，需要重新打包。 客户端可以引入网络资源，但是我这边没有网络资源的服务器用于部署这个。 在网上找了很久没有找到有人有同样的需求，没办法了只能想你请教了
> 
> 不好意思，这个场景我不太了解。

非常感谢你之前的解答，现在我改成了利用jsdelivr使用cdn的方式加载，但是现在出现了一个问题，由于我希望url地址不变，因此我使用jsdelivr的时候版本号使用的是latest，但是当unity加载时，相同路径的资源不会重新获取，只有当我手动切换版本号时才会重新获取，我在搜索资料时看到unity-webgl中有一个缓存选项，可选值为"must-revalidate" | "immutable" | "no-store"，不只我是否可以在使用你的组件时对缓存模式进行配置

**Comment by StarDamnSucks** [comment]
> > > 只要实例化配置的资源 path 不变，替换资源文件没有任何问题。 另：客户端也是可以引入网络资源的吧。
> > 
> > 
> > 资源path不变，但是我在electron的开发工具里看到的loader.js文件被打包进了asar中，我的文件资源在asar.unpacked中，所以一旦替换就不能正常运行，需要重新打包。 客户端可以引入网络资源，但是我这边没有网络资源的服务器用于部署这个。 在网上找了很久没有找到有人有同样的需求，没办法了只能想你请教了
> 
> 不好意思，这个场景我不太了解。

非常感谢你之前的解答，现在我改成了利用jsdelivr使用cdn的方式加载，但是现在出现了一个问题，由于我希望url地址不变，因此我使用jsdelivr的时候版本号使用的是latest，但是当unity加载时，相同路径的资源不会重新获取，只有当我手动切换版本号时才会重新获取，我在搜索资料时看到unity-webgl中有一个缓存选项，可选值为"must-revalidate" | "immutable" | "no-store"，不知我是否可以在使用你的组件时对缓存模式进行配置

**Comment by Meqn** [comment]
@StarDamnSucks 
不好意思，最近比较忙没怎么关注。
你的问题我不太理解，我没碰到过这种情况。 重新加载和创建Unity程序应该不会有问题。

**Comment by RichardsATcn** [comment]
> > @StarDamnSucks 你是要替换 unity资源文件？ 这个无法做到自动热更新，只能手动销毁和重建。
> > 本来vue组件想要做一个监听 unity资源地址变化，然后自动重载，但是想想没必要。因为资源更新了，其实资源地址是不变的。如果地址也要改变，相当于改变整个Unity应用实例了。这个只能重新创建新实例，Unity官方也不会提供方法，也没必要。
> > 不过可以在 `UnityWebgl.js` 内加一个 `reload(config)` 实例方法。 (你可以参考源码中的 `html` 示例)
> 
> 我是指unity的资源文件不与项目文件打包在一起，这样的话文件可以进行替换，像这样的几个文件 ![image](https://private-user-images.githubusercontent.com/12879803/242605292-a8ba5d2f-8d5e-486c-916a-7eb4d67b0668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTE4MjEsIm5iZiI6MTcyMTY1MTUyMSwicGF0aCI6Ii8xMjg3OTgwMy8yNDI2MDUyOTItYThiYTVkMmYtOGQ1ZS00ODZjLTkxNmEtN2ViNGQ2N2IwNjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDEyMzIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNWVhNjc2MzQ2OWM1YzZiMDg5NWYwOWMxOGNlMTM5ZGU1MmIzOTNkODU4OGEwMTk0YWM4ZDNkYjY4MmY1ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.56Dy4KJx32ly_iMbqsQdOrDF4ZUSXc2tpsReY7mFJSc) 当这些模型文件替换时unity可以加载新的资源文件，由于我这个是桌面端程序，不是web的，所以并不能使用cdn引入替换，非常感谢你的回答

您好，想要问问，您这截图里的文件是unityweb结尾的，是怎么配置到这个项目的 配置字段里的呢？
![image](https://github.com/user-attachments/assets/f009edc1-99b0-4335-ba0d-04dd1ae44cdb)
