### ISSUE TITLE
Vue 2 sample has some issue on running

### ISSUE THREAD

**Issue by GohChunFeng** [Meqn/UnityWebGL.js#28]
Hi, thanks for the effort for this plugin.
I tested the Vue 2 sample(https://stackblitz.com/edit/unity-webgl-vue2-demo?file=package.json) but I found that there is some issue might cause the webgl unable to render properly. 
![item missing](https://github.com/Meqn/UnityWebGL.js/assets/58229496/1e627a1e-a7df-428d-8bd5-f86d21ace351)
![error in console](https://github.com/Meqn/UnityWebGL.js/assets/58229496/cfa250e9-e026-4c8e-ac5a-1000d9edf6a0)
Can you help to check on this issue?
Thx in advance for the support.

**Comment by Meqn** [comment]
可能是package.json的`peerDependencies` 值配置有问题。
你手动安装 `@vue/composition-api` 即可。

![WX20230726-194401.png](https://s2.loli.net/2023/07/26/q9vcfxdBaImlCy4.png)

**Comment by GohChunFeng** [comment]
Thanks, I change the browser to test and able to get the result with the original sample code on the StackBlitz, but should I try to update the vue package to vue@2.6.14 and @vue/composition-api@1.7.1 ? 
Because when I do so it will prompt error like the one inside the picture I share before.
And i try to download the source code and run in the code editor, I faced problem when trying to run npm install with the original code, after I update the vue package to vue@2.6.14 and @vue/composition-api@1.7.1 , I got error when do npm run serve (if i don't change it and keep as vue@2.7.14 and @vue/composition-api@1.7.0 the npm install will have another problem)

![image](https://github.com/Meqn/UnityWebGL.js/assets/58229496/67d383bf-0973-4126-b11a-e10dfd9c5a42)

![image](https://github.com/Meqn/UnityWebGL.js/assets/58229496/6b173d27-5d4c-46f0-a7d6-c924e5f35b56)

**Comment by Meqn** [comment]
The online demo platform is somewhat problematic.

I suggest you create a project locally using vue-cli. I just tested it locally without any problem.

![WX20230727-100037@2x.png](https://s2.loli.net/2023/07/27/dGhCXBfqWaEQgTM.png)

**Comment by GohChunFeng** [comment]
Thanks. I tried with fresh new Vue 2 project created from vue cli, and able to render my unity webgl object successfully.  Thanks for the help, will close this issue.
