### ISSUE TITLE
监听不到unity暴露出的方法

### ISSUE THREAD

**Issue by layzf** [Meqn/UnityWebGL.js#30]
用C#开发的unity。
在web端使用window.xxx能监听到，使用插件的on('xxx')监听不到什么原因？

**Comment by layzf** [comment]
看了下.framework.js文件, 问题的出现是暴露的方法直接挂载到window上面，而我在插件里面，需要包一层对象，有没有什么办法，直接挂载到window。

**Comment by layzf** [comment]
有没有什么办法，直接挂载到window,而不是__UnityLib__（不需要包裹）对象下面。

**Comment by Meqn** [comment]
> 用C#开发的unity。 在web端使用window.xxx能监听到，使用插件的on('xxx')监听不到什么原因？

这个监听应该是没问题的 ，我公司的生产项目就这样用的。

如果直接绑定到window上，目前不可以。只能等更新版本了。

**Comment by layzf** [comment]
感谢回复，我让Unity工程师又嵌了一层对象，之前是直接挂载Window的。
