### ISSUE TITLE
Can't install with Nuxt 3.6.5 and Vue 3.3.4

### ISSUE THREAD

**Issue by dbaldwin** [Meqn/UnityWebGL.js#31]
Hi, first off great work! I have this working well with a Vue2 project. I'm upgrading my project to Nuxt 3.6.5 which runs on Vue3.3.4 and am receiving the following error:

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: nuxt-app@undefined
npm ERR! Found: vue@3.3.4
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.3.4" from @nuxt/vite-builder@3.6.5
npm ERR!   node_modules/@nuxt/vite-builder
npm ERR!     @nuxt/vite-builder@"3.6.5" from nuxt@3.6.5   
npm ERR!     node_modules/nuxt
npm ERR!       dev nuxt@"^3.6.5" from the root project    
npm ERR!       2 more (@nuxt/devtools, @nuxt/devtools-kit)
npm ERR!   peer vue@">=2.7 || >=3" from @unhead/vue@1.3.2 
npm ERR!   node_modules/@unhead/vue
npm ERR!     @unhead/vue@"^1.1.30" from nuxt@3.6.5
npm ERR!     node_modules/nuxt
npm ERR!       dev nuxt@"^3.6.5" from the root project
npm ERR!       2 more (@nuxt/devtools, @nuxt/devtools-kit)
npm ERR!   6 more (@vitejs/plugin-vue, @vitejs/plugin-vue-jsx, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! unity-webgl@"^3.5.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.7.0" from unity-webgl@3.5.1
npm ERR!     node_modules/unity-webgl
npm ERR!       unity-webgl@"^3.5.1" from the root project

I was trying to work on a fix with your repo, but when I clone it and run `npm install` I receive the following error:

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vue@3.3.4
npm ERR! node_modules/vue
npm ERR!   dev vue@"^3.2.38" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR! node_modules/@vue/composition-api
npm ERR!   dev @vue/composition-api@"^1.7.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

I'd love to help get this working in Vue3 if possible. Any guidance would be appreciated.

Thanks again!

**Comment by dbaldwin** [comment]
I see you're using pnpm which is new to me. But I got everything installed. I'm going to see if I can build and figure out how to make it work with my project. If you have any tips please let me know and I'll report back when I know more.

**Comment by Meqn** [comment]
> I see you're using pnpm which is new to me. But I got everything installed. I'm going to see if I can build and figure out how to make it work with my project. If you have any tips please let me know and I'll report back when I know more.

@dbaldwin 
From the error message you provided, I don't seem to see that the error is caused by the `unity-webgl`.

I suggest you try to create a new vue3 project and import `unity-webgl` to try to see if it works.

There is a vue3 example in the documentation: https://stackblitz.com/edit/unity-webgl-vue3-demo

**Comment by dbaldwin** [comment]
Yep. Works great in your Vue3 example and in a standalone project I spun up. For those that want to get this working with Nuxt3 here is what I had to do in my project:

```
npm install --force junity-webgl
```
and then I kept seeing the error "window is not defined" when accessing through localhost. I had to change my nuxt.config.ts to disable SSR like so:

```
export default defineNuxtConfig({
  devtools: { enabled: true },
  ssr: false,
});
```
I'm now up and running.

**Comment by Meqn** [comment]
> Yep. Works great in your Vue3 example and in a standalone project I spun up. For those that want to get this working with Nuxt3 here is what I had to do in my project:
> 
> ```
> npm install --force junity-webgl
> ```
> 
> and then I kept seeing the error "window is not defined" when accessing through localhost. I had to change my nuxt.config.ts to disable SSR like so:
> 
> ```
> export default defineNuxtConfig({
>   devtools: { enabled: true },
>   ssr: false,
> });
> ```
> 
> I'm now up and running.



Currently unity-webgl only runs in the browser, I'll support it in future releases.
