### ISSUE TITLE
Load local WebGL build

### ISSUE THREAD

**Issue by Xeyos88** [Meqn/UnityWebGL.js#33]
I am trying to load the indicated files of a WebGL build from local path. Neither with a new project, nor with the example works.

**Comment by Meqn** [comment]
Can you post the error message and code?

**Comment by Xeyos88** [comment]
404 file not found.
It seems that it still searches for them over the network and not locally

**Comment by Meqn** [comment]
Can you post the project directory structure and source code?

**Comment by Xeyos88** [comment]
Here the link for the source code. [link](https://drive.google.com/file/d/1FYr75i-GGv2JjVeTtfDmSGE-fryIKWEX/view?usp=sharing)

**Comment by Meqn** [comment]
You move the Build file to the public directory.

**Comment by Xeyos88** [comment]
Okay, how stupid of me, I didn't think of that

**Comment by Meqn** [comment]
Sometimes it may be overlooked.  💪🏻
