### ISSUE TITLE
Update suggestion for Input Keyboard problem

### ISSUE THREAD

**Issue by Xeyos88** [Meqn/UnityWebGL.js#34]
I wanted to suggest a small update.
Unity's canvas captures all the keyboard input that comes in. No longer being able to interact with the rest of the applioation.

To get around this problem in the Unity project you need to make a small change:
`  #if !UNITY_EDITOR && UNITY_WEBGL
  WebGLInput.captureAllKeyboardInput = false;
  #endif`

This causes Unity to no longer capture all input once the focus is lost, however, you can no longer reassign it.

To solve this problem it is nesessary to add the tabindex attribute to the canvas.
Then the library should directly generate the canvas with the attribute
`<canvas id="unity-canvas-1" style="width: 100%; height: 100%; cursor: default;" width="1689" height="356" tabindex="1"></canvas>`

**Comment by Meqn** [comment]
Okay, I'll post a version later

**Comment by Xeyos88** [comment]
I updated to version 3.5.3 but the tabindex attribute still seems not to be generated in the canvas tag
![image](https://github.com/Meqn/UnityWebGL.js/assets/16436299/a913ae56-15dc-47de-80f8-901f064426fb)

**Comment by Meqn** [comment]
Sorry, I just saw your reply.
There is a bug in the previously released v3.5.3, the tabindex type can only accept number type. You can upgrade to version v3.5.5.
