### ISSUE TITLE
There nothing in unity canvas T T

### ISSUE THREAD

**Issue by Edurle** [Meqn/UnityWebGL.js#35]
I have used the pluguin in Vue2 & Vue3 and it works well. But when i try to use it in a old version vue2(v2.6.11 and parser is "babel-eslint"), it doesn't work any more. It can render a canvas which id is "unity-canvas-1", but there are noting on the cavans; I debug it in console, it's unityInstance and unityLoader are all null. Can you plz tell me any solution to solve the problem?
last day：
I found in unity-webgl/vue/index.esm.js line 42: cavas.value is undefine. So the code in if condition never run;

onMounted(() => {
    var _a;
    if (canvas.value) {
        (_a = props.unity) === null || _a === void 0 ? void 0 : _a.create(canvas.value);
    }
});
Do you have some idea to solve it?

**Comment by Meqn** [comment]
@Edurle 
You need to install the `@vue/composition-api`
