### ISSUE TITLE
Loader problems with different games during same session

### ISSUE THREAD

**Issue by JoostKersjes** [Meqn/UnityWebGL.js#36]
Our case is a Vue3 SPA where users can play various different Unity games. Because it is an SPA, users can play different games within the same single session. When this happens, we see problems with loading any streaming assets, like translation files.

With this information, I started investigating the `loader` part.

This is what I've observed so far:

- The first game that loads creates 2 `<script>`s in the DOM, the `.loader.js` and the `.framework.js`.
- When the first game is unloaded (with `await unityContext.unload();`), both of these scripts disappear from the DOM.
- The second game that loads only creates 1 `<script>`, for the `.framework.js`.
- This second game mostly "works", but things like translations are not loaded.
- By looking at the network requests, I can see that the `.loader.js` code from the first game is reused from browser cache to load the second game.
- In the build files, I see that the `.loader.js` files of the two games are similar, but not identical. Because there is a difference, I expect that this reusing should not happen.
- Looking at the code, I think that this line is relevant: https://github.com/Meqn/UnityWebGL.js/blob/main/packages/lib/src/loader.ts#L28

If I change my code after `unload()` so that it sets `window.createUnityInstance = null`, then loading a second game will create the 2 `<script>`s and I don't see problems with translations anymore.

From what I understand, even if the `<script>` tag for the `.loader.js` is deleted, the `window.createUnityInstance` function will still exist in the browser's memory.

I'm not sure my solution of unsetting the `createUnityInstance` is correct, which is why I'm posting here.

Sorry that I don't have a reproduction. Hope this helps to clear up the issue.

**Comment by Meqn** [comment]
Great, there is no problem with this solution.
```
window.createUnityInstance = null
```

**Comment by JoostKersjes** [comment]
Thanks! Should this be adopted into the library, or is this too much of an edge case?

**Comment by Meqn** [comment]
Yes, this is a special case. Unlike your situation, which I encountered at work, the loader script did not need to be reloaded. 

So I'm thinking about how to better add it to the library.

Thank you for your suggestion.

**Comment by Meqn** [comment]
On balance, I deleted the loader script cache. Its actual benefit was too small, and there were no side effects from deleting it.

You can upgrade to `v3.5.4`.
