### ISSUE TITLE
unload function cause my page crashed

### ISSUE THREAD

**Issue by AbbetWang** [Meqn/UnityWebGL.js#37]
I have a situation where, after packaging my Unity project as WebGL and calling `unload` function, the tab in Google Chrome becomes unresponsive. The DevTools for that tab are also unavailable. When I check the Google Chrome Task Manager, I see that the CPU usage for that tab's process is around 100%. This issue seems to occur shortly after calling `unityInstance.quit`. How can I resolve this problem to prevent the webpage from freezing and consuming high CPU resources?

**Comment by Meqn** [comment]
I'm not experiencing this, can you provide an online example?

**Comment by imleeou** [comment]
I think the same thing happened to me. I wanted to destroy unity when I switched pages, so I called unload(), causing the browser TAB to freeze and become unresponsive.

**Comment by imleeou** [comment]
Check for a long time, found that it seems to be a problem with unity resources, I use oss resources in the author demo, there will be no tab page card dead problem, embarrassing.
`	loaderUrl: "https://static-huariot-com.oss-cn-hangzhou.aliyuncs.com/unity/test1/Build/OUT_BIM.loader.js",
	dataUrl: "https://static-huariot-com.oss-cn-hangzhou.aliyuncs.com/unity/test1/Build/OUT_BIM.data",
	frameworkUrl: "https://static-huariot-com.oss-cn-hangzhou.aliyuncs.com/unity/test1/Build/OUT_BIM.framework.js",
	codeUrl: "https://static-huariot-com.oss-cn-hangzhou.aliyuncs.com/unity/test1/Build/OUT_BIM.wasm"`
