### ISSUE TITLE
请问下，这种导出的unity目录还适用这个库吗

### ISSUE THREAD

**Issue by sunjiesama** [Meqn/UnityWebGL.js#8]
这是unity目录
![image](https://user-images.githubusercontent.com/54022918/187819106-9479d75a-3422-4b6b-997b-7d68d117c323.png)
loaderUrl,dataUrl,frameworkUrl,codeUrl这些和我目录下的文件好像都对应不上

**Comment by sunjiesama** [comment]
不好意思打扰了，第一次接触这个unity,一头雾水

**Comment by sunjiesama** [comment]
我知道了，是版本不对应

**Comment by Meqn** [comment]
你这个导出的目录是否可用，我不太清楚。你可以测试下

**Comment by sunjiesama** [comment]
> 你这个导出的目录是否可用，我不太清楚。你可以测试下

感谢回答

**Comment by RichardsATcn** [comment]
> 这是unity目录 ![image](https://user-images.githubusercontent.com/54022918/187819106-9479d75a-3422-4b6b-997b-7d68d117c323.png) loaderUrl,dataUrl,frameworkUrl,codeUrl这些和我目录下的文件好像都对应不上

我也是这种目录，请问你成功了嘛

**Comment by songsiqiu** [comment]
@sunjiesama @RichardsATcn 请问您成功了吗, 是怎么解决这个问题的
